
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Enable debug logging for modbus
logger:
  logs:
    homeassistant.components.modbus: debug
    pymodbus: debug

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
knx: !include knx.yaml
modbus: !include modbus.yaml
template: !include template.yaml
goecharger: !include goecharger.yaml
