sensor:
  - name: "Azimuth"
    state_address: "0/7/2"
    type: angle_deg
  - name: "Elevation"
    state_address: "0/7/3"
    type: angle_deg
  - name: "Helligkeit Sued"
    state_address: "0/7/25"
    type: illuminance 
  - name: "Helligkeit West"
    state_address: "0/7/26"
    type: illuminance 
  - name: "Helligkeit Ost"
    state_address: "0/7/27"
    type: illuminance 

weather:
  - name: "Meteodata 140"
    address_temperature: "0/7/8"
    address_brightness_south: "0/7/25"
    address_brightness_west: "0/7/27"
    address_brightness_east: "0/7/26"
    address_wind_speed: "0/7/6"
    address_rain_alarm: "0/7/11"
    address_frost_alarm: "0/7/16"
    address_wind_alarm: "0/7/13"

cover:
  - name: "Jalousie WC EG"
    device_class: "blind"
    travelling_time_up: 35
    travelling_time_down: 35
    move_long_address: "2/1/0"
    move_short_address: "2/1/1"
    position_address: "2/1/2"
    angle_address: "2/1/3"
    position_state_address: "2/6/2"
    angle_state_address: "2/6/3"

